language: node_js
node_js:
  - "7"
  - "6"
  - "4"
install:
  - npm install
cache:
  directories:
    - $HOME/.npm
notifications:
  email: false
addons:
  apt:
    packages:
      - oracle-java8-set-default